version: '2'
services:
  #nginx-proxy:
  #  image: jwilder/nginx-proxy
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami1:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=preprod.aa.com
  whoami2:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=preprod.aa.com
  adminer1:
    image: dehy/adminer:4.8.0
    environment:
      - VIRTUAL_HOST=preprod.aa.com,adminpre.aa.com


#docker pull jwilder/nginx-proxy
#docker pull dehy/adminer:4.8.0
#easymysql
#curl -is aa.com
