version: '2'
# sudo docker-compose -f docker-compose.scope.yml up -d
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  # localhost:4040
  # scope:
  #   image: weaveworks/scope:1.13.2
  #   #network_mode: "host"
  #   pid: "host"
  #   privileged: true
  #   labels:
  #     - "works.weave.role=system"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:rw"
  #   command:
  #     - "--probe.docker=true"
  #   environment:
  #     - VIRTUAL_HOST=scope.aa.com      