# https://hub.docker.com/r/aciklab/liman
# docker docker.io/gitea/gitea:1.22.6-rootless
# https://docs.gitea.com/installation/install-with-docker-rootless/
# grafana
---
version: "3"
services:
  gitea:
    container_name: gitea
    image: docker.io/gitea/gitea:1.22.6-rootless
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"