# https://hub.docker.com/r/linuxserver/freshrss
# docker pull ghcr.io/linuxserver/freshrss:amd64-version-1.18.1
# https://github.com/uGeek/docker-filebrowser/blob/main/docker-compose_filebrowser%2Bwebdav.yml
---
#name: demo3
services:
  filebrowser:
    image: hurlenko/filebrowser:v2.31.2
    #user: "${UID}:${GID}"
    ports:
      - 7000:8080
    volumes:
      - /opt/data:/data
      - /opt/data:/config
    environment:
      - FB_BASEURL=/
      #- FB_BASEURL=/filebrowser
    #restart: always

  nginx: # 172.23.0.2
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    #   args: 
    #     MYARGUMENTO: "Soy un argumento desde docker compose"
    image: ubuntu/nginx:1.24-24.04_edge
    #image: ubuntu/nginx:1.26-24.10_edge
    #restart: always
    environment: 
      MYVARIABLE: "este es un mensaje desde docker-compose"    
    ports:
      - 7001:80
    volumes: 
      - /opt/data/nginx:/var/www/html

  nginx2:
    image: ubuntu/nginx:1.24-24.04_edge
    ports:
      - 7002:80
    volumes: 
      - /opt/data/nginx2:/var/www/html

  caddy:
    image: caddy:2.4.3
    ports:
      - 7003:80
    volumes: 
      - /opt/data/caddy:/usr/share/caddy
      - /opt/data/config:/data

# https://dockge.kuma.pet/
# https://hub.docker.com/r/louislam/dockge
  dockge:
    #image: louislam/dockge:1.4.2 fail
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 7006:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/data:/app/data
      # Stacks Directory
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/stacks

  # freshrss:
  #   #image: ghcr.io/linuxserver/freshrss:amd64-version-1.18.1
  #   #image: ghcr.io/linuxserver/freshrss:1.25.0
  #   container_name: freshrss
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     - /opt/data/fresh:/config
  #   ports:
  #     - 7003:80
  #   restart: unless-stopped